name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci # Install dependencies in the cloud

      - name: Build
        env:
          VITE_AUTH_USERNAME: ${{ secrets.VITE_AUTH_USERNAME || 'admin' }}
          VITE_AUTH_PASSWORD_HASH: ${{ secrets.VITE_AUTH_PASSWORD_HASH || '88b0ca5f846091a2578af6fb8d6fd7cee236167bb7750919878b6b9d9874c4d7' }}
          VITE_SESSION_DURATION: ${{ secrets.VITE_SESSION_DURATION || '24' }}
        run: npm run build # Build the project, outputs to dist folder

      - name: Copy dist to docs
        run: |
          rm -rf docs # Clear existing docs folder
          mkdir -p docs
          cp -r dist/* docs/ # Copy contents of dist to docs

      - name: Create CNAME File
        run: echo "hellowereld.com" > docs/CNAME # Replace with your actual domain

      - name: Commit docs folder
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "Update docs folder with new build and CNAME" || echo "No changes to commit"
          git push origin main